### ISSUE TITLE
Namespace conflict: logstash_config

### ISSUE THREAD

**Issue by eherot** [sczizzo/magic-cookbook#5]
The most popular Logstash cookbook [lusis/chef-logstash](https://github.com/lusis/chef-logstash) uses the name `logstash_config` for one of its core resources. Given the likelihood that people who want to use your config generator are also going to be using that cookbook, I think it might be a good idea to pick a new, more generic name for this method (e.g. `logstash_config_hash`).

Thoughts?

cc @EdHurtig (my co-worker who first noticed this issue)

**Comment by sczizzo** [comment]
Thanks for the head's up. I've just released `v1.2` of the Magic cookbook, which renames the `logstash_config` generator to `logstash_typed_config`. Hope that helps!

**Comment by EdHurtig** [comment]
Thanks!

**Comment by eherot** [comment]
:guitar: :+1:
